[tool.poetry]
name = "kakomon-manager-legacy"
version = "0.1.0"
description = ""
authors = ["satackey"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
img2pdf = "^0.3.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
